swedenconnect/saml-identity-provider

autoconfigure/pom.xml
autoconfigure/src/main/java/se/swedenconnect/spring/saml/idp/autoconfigure/settings/IdentityProviderAutoConfiguration.java
pom.xml
saml-identity-provider/pom.xml
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/Saml2IdentityProviderVersion.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/authnrequest/validation/AbstractMessageReplayChecker.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/config/configurers/Saml2AuthnRequestAuthenticationProviderConfigurer.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/config/configurers/Saml2IdpConfigurerUtils.java
samples/client/pom.xml
samples/demo-boot-idp/pom.xml
samples/pom.xml
starter/pom.xml

@felix-hellman You should use `AbstractMessageReplayChecker` for your Redis-implementation in BankID IdP.

IS-6 FIxes for MessageReplayChecker

---

autoconfigure/pom.xml
pom.xml
saml-identity-provider/pom.xml
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/Saml2IdentityProviderVersion.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/authentication/Saml2UserAuthentication.java
samples/client/pom.xml
samples/demo-boot-idp/pom.xml
samples/pom.xml
starter/pom.xml

IS-10 Fixed serialization bug

---

autoconfigure/pom.xml
pom.xml
saml-identity-provider/pom.xml
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/audit/Saml2AuditEvent.java
saml-identity-provider/src/test/java/se/swedenconnect/spring/saml/idp/it/AuthenticationIntegrationTest.java
samples/client/pom.xml
samples/demo-boot-idp/pom.xml
samples/pom.xml
starter/pom.xml

IS-13 Fixed bug in audit logging

---

saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/attributes/nameid/DefaultNameIDGeneratorFactory.java

IS-17 Fixed bug in handling unspecified NameIDFormat

---

autoconfigure/pom.xml
autoconfigure/src/main/java/se/swedenconnect/spring/saml/idp/autoconfigure/settings/IdentityProviderAutoConfiguration.java
autoconfigure/src/main/java/se/swedenconnect/spring/saml/idp/autoconfigure/settings/MetadataConfigurationProperties.java
docs/configuration.md
pom.xml
saml-identity-provider/pom.xml
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/Saml2IdentityProviderVersion.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/config/configurers/Saml2IdpMetadataEndpointConfigurer.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/settings/MetadataSettings.java
samples/client/pom.xml
samples/demo-boot-idp/pom.xml
samples/pom.xml
starter/pom.xml

IS-20 Support for crypto methods in metadata

---

autoconfigure/pom.xml
pom.xml
saml-identity-provider/pom.xml
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/Saml2IdentityProviderVersion.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/authentication/provider/AbstractUserAuthenticationProvider.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/authentication/provider/PrincipalSelectionSsoVoter.java
saml-identity-provider/src/test/java/se/swedenconnect/spring/saml/idp/authentication/provider/PrincipalSelectionSsoVoterTest.java
samples/client/pom.xml
samples/demo-boot-idp/pom.xml
samples/pom.xml
starter/pom.xml

IS-24 Added PrincipalSelectionSsoVoter

---

saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/config/configurers/Saml2IdpMetadataEndpointConfigurer.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/settings/MetadataSettings.java

IS-27 support for security contact person

---

saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/authentication/Saml2ServiceProviderUiInfo.java
saml-identity-provider/src/test/java/se/swedenconnect/spring/saml/idp/authentication/Saml2ServiceProviderUiInfoTest.java

IS-29 Now handles Organization element when looking for displayName

---

autoconfigure/src/main/java/se/swedenconnect/spring/saml/idp/autoconfigure/settings/MetadataResolverConfiguration.java

IS-31 Fixed bug when there are more than one provider configured

---

autoconfigure/src/main/java/se/swedenconnect/spring/saml/idp/autoconfigure/settings/MetadataProviderConfigurationProperties.java
autoconfigure/src/main/java/se/swedenconnect/spring/saml/idp/autoconfigure/settings/MetadataResolverConfiguration.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/settings/MetadataProviderSettings.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/settings/MetadataProviderUtils.java

IS-45 It is now possible to skip hostname verification

---

pom.xml
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/web/filters/Saml2IdpMetadataEndpointFilter.java

IS-47 Works without md signing key

---

autoconfigure/pom.xml
pom.xml
saml-identity-provider/pom.xml
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/attributes/UserAttribute.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/attributes/eidas/CurrentAddress.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/attributes/eidas/DateOfBirth.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/attributes/eidas/EidasAttributeValue.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/attributes/eidas/EidasAttributeValueConverter.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/attributes/eidas/Gender.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/attributes/eidas/PersonIdentifier.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/attributes/eidas/PlaceOfBirth.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/attributes/eidas/TransliterationString.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/attributes/eidas/package-info.java
saml-identity-provider/src/test/java/se/swedenconnect/spring/saml/idp/attributes/UserAttributeTest.java
starter/pom.xml

IS-50 Support for eIDAS attribute values

---

saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/attributes/UserAttribute.java
saml-identity-provider/src/test/java/se/swedenconnect/spring/saml/idp/attributes/UserAttributeTest.java

IS-52 String values in UserAttribute

---

saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/response/Saml2ResponseSender.java

IS-56 No HTML encode of RelayState

---

saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/config/configurers/Saml2IdpMetadataEndpointConfigurer.java

IS-55 Now using correct namespace for digestmethod under enc.method.

---

autoconfigure/pom.xml
pom.xml
saml-identity-provider/pom.xml
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/Saml2IdentityProviderVersion.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/audit/repository/RedisListAuditEventRepository.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/audit/repository/RedissonTimeSeriesAuditEventRepository.java
samples/client/pom.xml
samples/demo-boot-idp/pom.xml
samples/pom.xml
starter/pom.xml

Include audit event type name in key to not create a conflict

---

docs/configuration.md

Fixes typo in configuration.md

---

autoconfigure/pom.xml
pom.xml
saml-identity-provider/pom.xml
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/Saml2IdentityProviderVersion.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/audit/data/Saml2AssertionAuditData.java
samples/client/pom.xml
samples/demo-boot-idp/pom.xml
samples/pom.xml
starter/pom.xml

fix: Audit loggning now handles all attribute value types

---

saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/events/Saml2ErrorResponseEvent.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/events/Saml2SuccessResponseEvent.java

fix: Assertion and Response supports serialization in events

---

autoconfigure/src/main/java/se/swedenconnect/spring/saml/idp/autoconfigure/settings/IdentityProviderAutoConfiguration.java
autoconfigure/src/main/java/se/swedenconnect/spring/saml/idp/autoconfigure/settings/IdentityProviderConfigurationProperties.java
pom.xml
saml-identity-provider/pom.xml
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/authnrequest/AuthenticationRequirements.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/authnrequest/AuthenticationRequirementsBuilder.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/authnrequest/Saml2AuthnRequestAuthenticationProvider.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/config/configurers/Saml2AuthnRequestAuthenticationProviderConfigurer.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/config/configurers/Saml2IdpMetadataEndpointConfigurer.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/error/Saml2ErrorStatus.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/extensions/UserMessageExtension.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/extensions/UserMessagePreprocessor.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/settings/IdentityProviderSettings.java
saml-identity-provider/src/main/resources/idp-errors/idp-error-messages.properties

feat: Added support for the UserMessage extension

---

autoconfigure/pom.xml
docs/release-notes.md
pom.xml
saml-identity-provider/pom.xml
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/Saml2IdentityProviderVersion.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/attributes/eidas/CountryString.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/attributes/eidas/EidasAttributeValueConverter.java
saml-identity-provider/src/test/java/se/swedenconnect/spring/saml/idp/attributes/UserAttributeTest.java
samples/client/pom.xml
samples/demo-boot-idp/pom.xml
samples/pom.xml
starter/pom.xml

Added support for optional eIDAS attributes

---

autoconfigure/pom.xml
docs/release-notes.md
pom.xml
saml-identity-provider/pom.xml
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/Saml2IdentityProviderVersion.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/audit/repository/FileBasedAuditEventRepository.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/audit/repository/FilteringAuditEventRepository.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/audit/repository/MemoryBasedAuditEventRepository.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/audit/repository/RedisListAuditEventRepository.java
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/audit/repository/RedissonTimeSeriesAuditEventRepository.java
samples/client/pom.xml
samples/demo-boot-idp/pom.xml
samples/pom.xml
starter/pom.xml

IS-91 Made sure multiple log entries were not produced

---

autoconfigure/src/main/java/se/swedenconnect/spring/saml/idp/autoconfigure/audit/AuditRepositoryAutoConfiguration.java
autoconfigure/src/main/java/se/swedenconnect/spring/saml/idp/autoconfigure/audit/AuditRepositoryConfigurationProperties.java
docs/configuration.md
docs/release-notes.md
saml-identity-provider/pom.xml
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/audit/repository/LoggerAuditEventRepository.java
saml-identity-provider/src/test/java/se/swedenconnect/spring/saml/idp/audit/repository/LoggerAuditEventRepositoryTest.java
saml-identity-provider/src/test/java/se/swedenconnect/spring/saml/idp/audit/repository/MemoryAppender.java

IS-93 Audit logging to log system

---

autoconfigure/pom.xml
autoconfigure/src/main/java/se/swedenconnect/spring/saml/idp/autoconfigure/redis/RedissonActivationAutoConfiguration.java
autoconfigure/src/main/java/se/swedenconnect/spring/saml/idp/autoconfigure/redis/RedissonExtensionsAutoConfiguration.java
autoconfigure/src/main/java/se/swedenconnect/spring/saml/idp/autoconfigure/redis/RedissonFilter.java
autoconfigure/src/main/resources/META-INF/spring.factories
autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
pom.xml
saml-identity-provider/pom.xml
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/Saml2IdentityProviderVersion.java
samples/client/pom.xml
samples/demo-boot-idp/pom.xml
samples/demo-boot-idp/src/main/resources/application.yml
samples/pom.xml
starter/pom.xml

IS-96 Disabled Redisson autoconfiguration if Redis is not configured

---

autoconfigure/pom.xml
docs/release-notes.md
pom.xml
saml-identity-provider/pom.xml
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/Saml2IdentityProviderVersion.java
saml-identity-provider/src/main/resources/idp-errors/idp-error-messages_sv.properties
samples/client/pom.xml
samples/demo-boot-idp/pom.xml
samples/pom.xml
starter/pom.xml

IS-99 Swedish error messages

---

saml-identity-provider/pom.xml
saml-identity-provider/src/test/resources/logback-test.xml

IS-104 Fixed logback related logging issues in tests

---

autoconfigure/pom.xml
autoconfigure/src/main/java/se/swedenconnect/spring/saml/idp/autoconfigure/redis/RedissonActivationAutoConfiguration.java
autoconfigure/src/main/java/se/swedenconnect/spring/saml/idp/autoconfigure/redis/RedissonCondition.java
docs/release-notes.md
pom.xml
saml-identity-provider/pom.xml
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/Saml2IdentityProviderVersion.java
samples/client/pom.xml
samples/demo-boot-idp/pom.xml
samples/pom.xml
starter/pom.xml

IS-108 Fixed Redis cluster bug

---

docs/configuration.md

IS-107 Corrected default values

---

autoconfigure/pom.xml
autoconfigure/src/main/java/se/swedenconnect/spring/saml/idp/autoconfigure/settings/CredentialConfiguration.java
docs/release-notes.md
pom.xml
saml-identity-provider/pom.xml
saml-identity-provider/src/main/java/se/swedenconnect/spring/saml/idp/Saml2IdentityProviderVersion.java
saml-identity-provider/src/main/resources/idp-errors/idp-error-messages_sv.properties
samples/client/pom.xml
samples/demo-boot-idp/pom.xml
samples/pom.xml
starter/pom.xml

IS-118 Fixed errors when using "old" way of configuring credentials
